const occupations = [
    'Abogado',
    'Actor',
    'Adm. de empresas',
    'Adm. de servicios',
    'Adm. empresas turismo',
    'Adm. negocios internac',
    'Adm. turistico',
    'Adm. universitario empr.',
    'Administrador publico',
    'Agente viajero-seguros',
    'Agricultor',
    'Agronomo',
    'Analista prog.computacio.',
    'Arquitecto',
    'Artesano',
    'Artista',
    'Asistente social',
    'Astronomo',
    'Auditor',
    'Auxiliar de enfermeria',
    'Bibliotecologo',
    'Bioquimico',
    'Ciencias poli. y adminis.',
    'Comerciante',
    'Comisionista',
    'Comunicador dig. multime',
    'Constructor civil',
    'Contador auditor',
    'Contador m.legis.trib',
    'Contador publico',
    'Contador publico auditor',
    'Contador publico y auditor',
    'Contratista',
    'Corredor de propiedades',
    'Dentista',
    'Deportista',
    'Detective',
    'Dibujante',
    'Dibujante arquitect. estr',
    'Dibujante proyectista',
    'Dietista',
    'Disenador',
    'Duena de casa',
    'Economista',
    'Ed. fisica',
    'Educ.musica preesc y basi',
    'Educadora de parvulos',
    'Electricista',
    'Empleado',
    'Empresario',
    'Empresario loc. colectiva',
    'Enfermera',
    'Entrenador',
    'Estadistico',
    'Estudiante',
    'F.f.a.a. y carabineros',
    'Fonoaudiologo',
    'Geografia',
    'Geologo',
    'Industrial',
    'Ing. adm industrial',
    'Ing. adm. agroindustrial',
    'Ing. adm. de empresas',
    'Ing. adm. de recursos humanos',
    'Ing. agronegocios',
    'Ing. agronomica',
    'Ing. ambiental',
    'Ing. aut. de procesos industri',
    'Ing. aut. indument. y control',
    'Ing. automatizacion contr',
    'Ing. biotecnologia molecu',
    'Ing. civil agricola',
    'Ing. civil ambiental',
    'Ing. civil bioinformatica',
    'Ing. civil bioquimico',
    'Ing. civil biotecnologia',
    'Ing. civil compu. e informatica',
    'Ing. civil electrica',
    'Ing. civil electronica',
    'Ing. civil eletricidad',
    'Ing. civil en geografia',
    'Ing. civil en minas',
    'Ing. civil indus. de la madera',
    'Ing. civil industrial',
    'Ing. civil industrias',
    'Ing. civil infor. y telecom.',
    'Ing. civil informatica',
    'Ing. civil mecanica',
    'Ing. civil metalurgica',
    'Ing. civil obras civiles',
    'Ing. civil quimico',
    'Ing. civil sonido y acustica',
    'Ing. civil telematica',
    'Ing. comercio exteri',
    'Ing. comercio internacional',
    'Ing. comput e inform',
    'Ing. computacion',
    'Ing. construccion',
    'Ing. ejec. adm. agroindus',
    'Ing. ejec. adm. industria',
    'Ing. ejec. adm. men adm publ',
    'Ing. ejec. admi. empresas',
    'Ing. ejec. adminis.negoci',
    'Ing. ejec. administracion',
    'Ing. ejec. comer. internacional',
    'Ing. ejec. comput e infor',
    'Ing. ejec. control gestion',
    'Ing. ejec. electricidad',
    'Ing. ejec. electronica',
    'Ing. ejec. en minas',
    'Ing. ejec. geomensura',
    'Ing. ejec. gestion industrial',
    'Ing. ejec. industrial',
    'Ing. ejec. industrias',
    'Ing. ejec. informatica',
    'Ing. ejec. mantenim indus',
    'Ing. ejec. mec. proc. y mant. ind.',
    'Ing. ejec. metalurgica',
    'Ing. ejec. minas y metal',
    'Ing. ejec. prevenc riesgo',
    'Ing. ejec. quimica',
    'Ing. ejec.control instrum',
    'Ing. ejec.mecanica',
    'Ing. electricidad',
    'Ing. electricidad y electronico',
    'Ing. electrico',
    'Ing. electronico',
    'Ing. en acuicultura',
    'Ing. en alimentos',
    'Ing. estadistico',
    'Ing. forestal',
    'Ing. geomensura',
    'Ing. geomensura y cartografia',
    'Ing. gestion informatica',
    'Ing. gestion logistica',
    'Ing. gestion publica',
    'Ing. industri alimentaria',
    'Ing. industrial',
    'Ing. informac contro gest',
    'Ing. informatico',
    'Ing. informatico y gestion',
    'Ing. logistico',
    'Ing. maq.vehi.automotriz',
    'Ing. marina mercante',
    'Ing. marketing',
    'Ing. matematicas',
    'Ing. mec automo autotroni',
    'Ing. mecanico',
    'Ing. metalurgico',
    'Ing. minas y metalur',
    'Ing. negocios internacion',
    'Ing. prev de riesgos',
    'Ing. proy. industriales',
    'Ing. quimica industrial',
    'Ing. quimico',
    'Ing. rec. nat. renovables',
    'Ing. refrig climatizacion',
    'Ing. seg. y prev. de riesgos',
    'Ing. telecom. conect. y redes',
    'Ing. telecomunicaciones',
    'Ing. transito',
    'Ing. transporte transito',
    'Ing. transporte y t.',
    'Ing.conectividad y redes',
    'Ingeniero',
    'Ingeniero agronomo',
    'Ingeniero civil',
    'Ingeniero comercial',
    'Jubilado',
    'Kinesiologo',
    'Laboratorista',
    'Licenc. en letras',
    'Licenc. linguistic ingles',
    'Locutor',
    'Matematico y estadistico',
    'Matrona',
    'Mecanico',
    'Medico',
    'Nutricionista',
    'Obstetra y puericult',
    'Odontologo',
    'Pedag. automatizac',
    'Pedag. biol.fisic.quimica',
    'Pedag. ed diferencial',
    'Pedag. ed tecn prof',
    'Pedag. edu.fis.dep.recrea',
    'Pedag. educacio. especial',
    'Pedag. en ciencias',
    'Pedag. en edu. basica',
    'Pedag. en edu. fisica',
    'Pedag. en edu. parvularia',
    'Pedag. en ingles ens. basic. y med.',
    'Pedag. en quimica',
    'Pedag. ingle frances alem',
    'Pedag. lengua cult ingles',
    'Pedag. mat.fis.computac',
    'Pedag. matem y comp',
    'Pedag. med.cs.nat biolog',
    'Periodista',
    'Piloto',
    'Pintor',
    'Profes. area informatica',
    'Profesor',
    'Programa form.pedagogica',
    'Programa pedag.ed.media',
    'Psicopedagogo',
    'Publicista',
    'Quimico analista',
    'Quimico farmaceutico',
    'Quimico laboratorista',
    'Relacionador publico',
    'Rentista',
    'Secretaria',
    'Sicologo',
    'Socio de firma',
    'Sociologo',
    'Taxista',
    'Tecn. admin. rrhh',
    'Tecn. admin.financiera',
    'Tecn. admin.redes computa',
    'Tecn. comex',
    'Tecn. construccion',
    'Tecn. electri. y electro.',
    'Tecn. en informatica',
    'Tecn. en telecomunicaciones',
    'Tecn. en topografia',
    'Tecn. instrum.auto.cont.i',
    'Tecn. prevencion riesgos',
    'Tecn. univ. construccion',
    'Tecn. univ. electricidad',
    'Tecn. univ. electronica',
    'Tecn. univ. instr. auto',
    'Tecn. univ. mec.automotr',
    'Tecn. univ. mec.industria',
    'Tecn. univ. prev. riesgos',
    'Tecn. univ. proyect.ingen',
    'Tecn. univ. quimica',
    'Tecnico',
    'Tecnologo medico',
    'Telefonista',
    'Terapeuta ocupacional',
    'Topografo',
    'Trabajo social',
    'Transportista',
    'Vendedor',
    'Veterinario',
  ];
  
export default occupations;
  